20240901_085854 (update_mon)

diff --git a/askpass b/askpass
--- a/askpass
+++ b/askpass
@@ -41,7 +41,7 @@ thanks antofthy
 
 # usage
 
-% askpass [-f] [prompt]
+% askpass [-f | --nosd] [p_text]
 ## -f forces non systemd version
 
 # '
@@ -54,14 +54,19 @@ set -o pipefail
 unset PWORD
 PWORD=
 
+
 # hardcoded variables
-prompt='pwd '
+
 sd_bin='/bin/systemd-ask-password'
-sd_prompt=''
+
+## prompt icon
+p_icon='🔐'
+
+## file descriptor
 fd='5'
 
 
-check_tty()
+check_tty ()
 {
     if ! tty >/dev/null; then
 
@@ -73,32 +78,44 @@ check_tty()
 }
 
 
-sd_ask()
+sd_ask ()
 {
-    if [ "X$1" = "X-f" ]; then
+    case "$1" in
 
-	# execute non systemd version
-	shift
-	ask $1
+	-f | --nosd)
+	    ## force non systemd version
+	    shift
+	    sudo -v
+	    p_text="$@"
 
-    elif [ -x $sd_bin ]; then
+	    ask $p_text
+	    ;;
 
-	# execute systemd-ask-password
-	stty_0=$(stty -g)
-	trap 'stty "$stty_0"' EXIT
-	sudo $sd_bin --timeout=0 "${1:-$sd_prompt}"
-	## 20240620 before systemd v256:
-	#$sd_bin --timeout=0 "${1:-$sd_prompt}"
+	*)
+	    if [ -x $sd_bin ]; then
+		# execute systemd-ask-password (default)
 
-    fi
+		p_text="$@"
+
+		stty_0=$(stty -g)
+		trap 'stty "$stty_0"' EXIT
+		sudo $sd_bin --echo=masked --timeout=0 "$p_text "
+
+	    else
+
+		printf "$sd_bin not found\n"
+		exit 56
+
+	    fi
+	    ;;
+
+    esac
 }
 
 
-ask()
+ask ()
 {
-    ## hashtag designates non systemd (which shows *) version
-    prpt="${*:-$prompt}"
-    star='#'
+    # execute non-systemd ask password (askpass -f)
 
     # grab the current TTY settings
     # save stdout (for password result) to descriptor 3
@@ -108,10 +125,9 @@ ask()
     ## #exec $fd>&1 </dev/tty >/dev/tty
     stty_0=$(stty -g)
 
-    # resume stty_0 state on exit
+    ## resume stty_0 state on exit
     trap 'stty "$stty_0"' EXIT
     trap 'exit 10' HUP INT QUIT ABRT TERM
-    #trap 'echo "===INTERUPT==="; exit 10' HUP INT QUIT ABRT TERM
 
     # turn off echo and control character handling...
     # this stops BASH constantly switching terminal modes
@@ -119,45 +135,51 @@ ask()
     # user still have characters echoed between reads
     # -icanon	enable special characters: erase, kill, werase, rprnt
     stty -icanon -echo
-    #stty -echo
 
-    # prompt and read password one character at a time
-    echo -n "$prpt"
-    while IFS= read -r -n 1 char; do
+    ## systemd feedback char:     •
+    ## non-systemd feedback char: #
+    star='#'
+
+    ## reversed prompt icon to indicate non systemd version
+    echo -ne "\e[7m$p_icon\e[0m \e[1m$p_text\e[0m "
+
+    ## read password one character at a time
+    while IFS= read -r -n 1 -s char; do
 
 	# convert users key press to hexadecimal character code
 	# note a 'return' or EOL, will return a empty string
 	#code=$( echo -n "$char" | od -An -tx1 | tr -d ' \011' )
 	code=${char:+$(printf '%02x' "'$char'")}
 
-	# [DEBUG]
-	#echo -n "'$code'"
-
 	case "$code" in
+	    ## UTF-8 code units
 
-	    ''|0a|0d)
-		# finish on EOF, linefeed, or return
+	    '' | 0a | 0c | 0d)
+		## finish on:
+		## 0a linefeed (EOL)
+		## 0c formfeed (FF)
+		## 0d carriage return (CR)
 		break
 		;;
 
 	    03)
-		# ^C Interrupt
-		error_exit=true
+		## C-c interrupt
 		break
 		;;
 
-	    08|7f)
-		# Backspace or Delete
+	    08 | 7f)
+		## 08 backspace
+		## 7f backspace removes last character
 		if [ -n "$PWORD" ]; then
 
-		    PWORD="$( echo "$PWORD" | sed 's/.$//' )"
+		    PWORD="$(echo "$PWORD" | sed 's/.$//')"
 		    echo -n $'\b \b'
 
 		fi
 		;;
 
 	    15)
-		# ^U or kill line
+		## c-u kill line
 		echo -n "$PWORD" | tr -c '\010' '\010'  # backspace
 		echo -n "$PWORD" | tr -c ' '    ' '     # clear stars
 		echo -n "$PWORD" | tr -c '\010' '\010'  # backspace
@@ -165,13 +187,15 @@ ask()
 		PWORD=''
 		;;
 
+	    #[*)
 	    [01]?)
 		# ignore all other control characters
 		;;
 
 	    *)
-		# Normal char - record it
-		PWORD="$PWORD$char"
+		## save entered normal char to PWORD
+		#PWORD="$PWORD$char"
+		PWORD+="$char"
 		echo -n "$star"
 		;;
 
@@ -180,32 +204,23 @@ ask()
     done
 
 
-    # return tty to normal, cancel exit trap
+    ## return tty to normal
     stty "$stty_0"
+    ## cancel exit trap
     trap - EXIT HUP INT QUIT TERM
-
-    # remove all the stars now that the input is finished (same as '15' above)
-    #echo -n "$PWORD" | tr -c '\010' '\010'  # backspace
-    #echo -n "$PWORD" | tr -c ' '    ' '     # clear stars
-    #echo -n "$PWORD" | tr -c '\010' '\010'  # backspace
-    #echo -n "$PWORD" | sed 's//\cH \cH/g'
-    #echo ""  # "===password accepted===" ;;
-
-    # erase line
-    printf "\r"; tput el
+    ## newline
+    echo
 
     # output the resulting password to the original stdout
-    echo -n "$PWORD"
-    ## #echo -n "$PWORD" >&$fd
-
-    exit 0
+    echo "$PWORD"
 }
 
 
-main()
+main ()
 {
     check_tty
     sd_ask $@
+    exit 0
 }
 
 main $@
