20250404_080644_67EF76F4 (update_mon)

diff --git a/build-repo b/build-repo
--- a/build-repo
+++ b/build-repo
@@ -74,6 +74,13 @@ getargs ()
 		no_aur_pkgs=1
 		;;
 
+	    --download-missing|--down-miss|--dl )
+		## download files expected to be in pkgs
+		shift
+
+		download_missing=1
+		;;
+
 	    - )
 		shift
 
@@ -98,6 +105,8 @@ process_args ()
     # [[ -n $arg_repo_dst ]] && repo_dst="$(realpath $arg_repo_dst)"
     # [[ -n $arg_db_name ]] && db_name="$(realpath $arg_db_name)"
     # [[ -n $arg_db_dst ]] && db_dst="$(realpath $arg_db_dst)"
+
+    timestamp="$(date +'%Y%m%dT%H%M%S')"
 
     ## compulsory user arguments
     ### sort package list
@@ -180,7 +189,9 @@ build_dump_list ()
 	if [[ -z "$no_ofcl_pkgs" ]]; then
 	    ## do search official packages
 
-	    if pacman -Qqn "$pkg_name"; then
+	    abs_db_path=$(realpath $repo_ofcl_db)
+	    abs_cache_path=$(realpath $repo_ofcl_pkgs)
+	    if pacman -Qqn --dbpath "$abs_db_path" --cachedir "$abs_cache_path" "$pkg_name"; then
 
 		#TODO DEV no_ofcl to skip official packages
 
@@ -193,7 +204,10 @@ build_dump_list ()
 	elif [[ -z "$no_aur_pkgs" ]]; then
 	    ## do search aur packages
 
-	    if pacman -Qqm "$pkg_name"; then
+	    ## pacman needs absolute paths
+	    abs_db_path=$(realpath $repo_ofcl_db)
+	    abs_cache_path=$(realpath $repo_ofcl_pkgs)
+	    if pacman -Qqm --dbpath "$abs_db_path" --cachedir "$abs_cache_path" "$pkg_name"; then
 
 		#TODO DEV no_aur to skip aur packages
 
@@ -247,7 +261,9 @@ copy_pkg_files ()
 	if [[ -z "$no_ofcl_pkgs" ]]; then
 	    ## do search official packages
 
-	    if pacman -Qqn "$pkg_name"; then
+	    abs_db_path=$(realpath $repo_ofcl_db)
+	    abs_cache_path=$(realpath $repo_ofcl_pkgs)
+	    if pacman -Qqn --dbpath "$abs_db_path" --cachedir "$abs_cache_path" "$pkg_name"; then
 		## native package
 
 		latest_pkg=$(pacman -S --print "$pkg_name")
@@ -285,6 +301,26 @@ copy_pkg_files ()
 		## remove file:// prefix if applicable
 		latest_pkg=$(sed 's#^file://##' <<< "$latest_pkg")
 
+		## verify package integrity
+		## to prevent repo-add error:
+		## bsdtar: Error opening archive: Unrecognized archive format
+		## ==> ERROR: 'libsysprof-capture-48.0-1-x86_64.pkg.tar.zst' is not a package file, skipping
+		if ! file "$latest_pkg" | grep 'Zstandard compressed data'; then
+
+		    printf 'ERROR file integrity: %s' "$latest_pkg"
+		    #TODO add to error log
+		    printf ' ...adding to https_list\n'
+
+		    ## https:// list of packages whose zst is not in pkgs
+		    ## these files can later be downloaded via download-missing
+		    append_https_list
+
+		fi
+
+		#TODO
+		   ## ==> Adding package 'pkgs/e2fsprogs-1.47.2-1-x86_64.pkg.tar.zst'
+		   # ==> WARNING: A newer version for 'e2fsprogs' is already present in database
+
 		if [[ -n "$latest_pkg" ]]; then
 
 		    latest_pkg_realpath="$(realpath $latest_pkg)"
@@ -301,6 +337,12 @@ copy_pkg_files ()
 
 			fi
 
+		    elif [[ "$latest_pkg" =~ https:// ]]; then
+
+			## https:// list of packages whose zst is not in pkgs
+			## these files can later be downloaded via download-missing
+			append_https_list
+
 		    fi
 
 		else
@@ -314,7 +356,9 @@ copy_pkg_files ()
 	elif [[ -z "$no_aur_pkgs" ]]; then
 	    ## do search aur packages
 
-	    if pacman -Qqm "$pkg_name"; then
+	    abs_db_path=$(realpath $repo_ofcl_db)
+	    abs_cache_path=$(realpath $repo_ofcl_pkgs)
+	    if pacman -Qqm --dbpath "$abs_db_path" --cachedir "$abs_cache_path" "$pkg_name"; then
 		## aur package
 
 		copy_yay_source "$pkg_name"
@@ -324,6 +368,33 @@ copy_pkg_files ()
 	fi
 
     done < "$pkgs_2_copy"
+}
+
+
+append_https_list ()
+{
+    ## https:// list of packages whose zst is not in pkgs
+    ## these files can later be downloaded via download-missing
+    printf '%s\n' "$latest_pkg" >> "$repo_ofcl"/"$timestamp"_https.list
+    printf '%s\n' "$latest_pkg.sig" >> "$repo_ofcl"/"$timestamp"_https.list
+
+    printf '%s %s added to %s\n' "$pkg_name" "$pkg_version" "$repo_ofcl"/"$timestamp"_https.list
+}
+
+
+download_missing ()
+{
+    ## download missing packages with their signatures
+    if [[ "$download_missing" -eq 1 ]]; then
+
+       while IFS= read -r url; do
+
+	   printf '%s\n' "$url"
+	   curl -O "$url" -C - --output-dir ofcl/pkgs
+
+       done < "$repo_ofcl"/"$timestamp"_https.list
+
+    fi
 }
 
 
@@ -339,8 +410,20 @@ copy_yay_source ()
 
 create_repo_database ()
 {
+    ## check for stowaway files in package cache
+    stowaways=$(find "$repo_ofcl_pkgs" -maxdepth 1 -type f \
+		     ! -name '*.sig' \
+		     ! -name '*.pkg.tar.gz' \
+		     ! -name '*.pkg.tar.xz' \
+		     ! -name '*.pkg.tar.zst' \
+	     )
+
+    [[ -n "$stowaways" ]] \
+	&& printf 'ERROR stowaways detected in package cache (%s):\n%s\n' "$repo_ofcl_pkgs" "$stowaways" \
+	&& exit 88
+
     ## don't use exclusion patterns (like [^.sig]) because repo-add errors out on everything it can't read
-    "$repo_ofcl_pkgs"/*.{gz,xz,zst} \
+    "$repo_ofcl_pkgs"/*.pkg.tar.zst \
 	| repo-add --new --include-sigs "$repo_ofcl_db"/"$repo_ofcl_db_name".db.tar.zst
 }
 
@@ -373,6 +456,7 @@ main ()
     build_dump_list
     optimize_pkgs_dump_list
     copy_pkg_files
+    download_missing
     create_repo_database
     copy_sync_database
     check_mountpoint_ro
