20230827_110753 (update_mon)

diff --git a/cryptr b/cryptr
--- a/cryptr
+++ b/cryptr
@@ -22,10 +22,14 @@ set -o pipefail
 ### --------------------------------
 ### usage:
 ### -e encrypt a file or dir
-### cryptr [-e] <src> [dest]
+### cryptr [-e] <src> [srcs] [dest]
 ###
 ### -d decrypt a tarx file
 ### cryptr [-d] <src> [dest]
+###
+### examples:
+### cryptr src1
+### cryptr src1 explicit.dst
 ### --------------------------------
 ###
 ### WARNING! risk in multi-user systems!
@@ -34,7 +38,6 @@ set -o pipefail
 ##
 #
 
-# TODO overwrite option -O --overwrite
 
 # initial definitions
 ## select cipher suite
@@ -226,7 +229,7 @@ arguments() {
 
     ## getting operation, source and destination
 
-    declare -a src_arr=()
+    src_arr=()
 
     ## iterate over (non-associative) array ($args_arr)
     ## which values are entered arguments
@@ -236,6 +239,8 @@ arguments() {
 
 	unset arguments_continue
 	unset arg_was_src
+	unset src_is_dst
+	unset custom_dst
 
 	## determine operation if not already known
 	[[ -z "$opr" ]] && operation
@@ -251,8 +256,8 @@ arguments() {
 	## destination file
 	get_destination
 
-	## create inner tar file (encryption only)
-	#create_inner_tar
+	## create source tar file (encryption only)
+	#create_source_tar
 
     done
 }
@@ -278,13 +283,17 @@ get_source() {
 	## element is an existent file or directory to encrypt
 	src_validate
 
-	## append element to (non-associative) array $src_arr
-	src_arr+=("$src")
+	if [[ -z $src_is_dst ]]; then
 
-	## populate src_info
-	add_to_src_info
+	    ## append element to (non-associative) array $src_arr
+	    src_arr+=("$src")
 
-	arg_was_src=1
+	    ## populate src_info
+	    add_to_src_info
+
+	    arg_was_src=1
+
+	fi
 
     fi
 }
@@ -316,12 +325,15 @@ get_destination() {
 
 		    ## declare $arg as destination
 		    dst_arg="$arg"
+		    custom_dst=1
 
 		else
 
 		    ## no destination given
-		    ## first element value will be the name of the destination
-		    dst_arg="${args_arr[0]}.tarx"
+		    ## first source element value
+		    ## will be the name of the destination
+		    dst_arg="${src_arr[0]}"
+		    #dst_arg="${src_arr[0]}.tarx"
 
 		fi
 
@@ -368,26 +380,6 @@ get_destination() {
 }
 
 
-create_inner_tar() {
-    ## in case of encryption
-    if [[ "$opr" == 'e' ]] || [[ "$opr" == 'c' ]]; then
-
-	case "$arg_index" in
-
-	    0)
-		tar_create
-		;;
-
-	    *)
-		tar_append
-		;;
-
-	esac
-
-    fi
-}
-
-
 src_validate() {
 
     ## write full src path
@@ -396,19 +388,35 @@ src_validate() {
     ## src does not exist
     if [[ ! -f $src ]] && [[ ! -d $src ]] ; then
 
-	printf "${MAGENTA}%s${NOC} source file not found\n" "$src"
-	exit 5
+	## if element is the last element (last argument)
+	## but not the only argument
+	if [[ "$arg_index" == "$last_element_index" ]] && \
+	       [[ "$last_element_index" -gt 0 ]]; then
+
+	    ## current $arg should be destination
+	    src_is_dst=1
+	    get_destination
+	    continue
+
+	else
+
+	    printf "${MAGENTA}%s${NOC} source file not found\n" "$src"
+	    exit 5
+
+	fi
 
     elif [[ -z $src ]]; then
 
 	printf "${MAGENTA}source & destination${NOC} files missing\n"
 	exit 5
 
-    fi
+    else
 
-    ## set source directory and target names
-    src_sub_dir=$(dirname $src)
-    src_tar_get=$(basename $src)
+	## set source directory and target names
+	src_sub_dir=$(dirname $src)
+	src_tar_get=$(basename $src)
+
+    fi
 }
 
 
@@ -481,7 +489,17 @@ dst_validate() {
     fi
 
     ## rewrite dst (full path)
-    dst="$(realpath $dst_sub_dir/$dst_tar_get)"
+    if [[ -n $custom_dst ]]; then
+
+	## a custom destination is given as argument
+	dst="$(realpath $dst_sub_dir/$dst_tar_get)"
+
+    else
+
+	## no destination argument is given
+	dst="$(realpath $dst_sub_dir/$dst_tar_get).tarx"
+
+    fi
 
     ## if $dst already exists
     [[ -f $dst ]] && \
@@ -546,25 +564,53 @@ show_info() {
 }
 
 
-tar_create() {
+: '
+# collect_names
 
-    # (inner) tar file
-    # will be wrapped in tarx
-    tar_file=$tmp_dir/$src_tar_get.inner.tar
-    mkdir -p $(dirname $tar_file)
+## source paths are elements in source array
+all source elements "${src_arr[@]}"
+number of elements "${#src_arr[@]}"
+first element "${src_arr[0]}"
+last element "${src_arr[@]}"
 
-    ## create (inner) tar archive
-    tar --create -f $tar_file -C $src_sub_dir $src_tar_get
-}
+## destination
+path and filename "$dst"
+directory "$dst_sub_dir"
+filename "$dst_tar_get"
+contains "$tar_src.crypt" and "$cipher_select_file"
+
+## temporary directory
+path "$tmp_dir"
+
+## tar with source paths
+plain "$tar_src" in "$tmp_dir"
+definition in tar_append() tar_src=$tmp_dir/$dst_tar_get
+encrypted "$tar_src.crypt" in "$dst"
+
+## cipher select file
+plain "$cipher_select_file" in "$dst"
+
+## encryption
+file_in="$tmp_dir/$tar_src"
+file_out="$tmp_dir/${dst_tar_get}.crypt"
+# '
 
 
 tar_append() {
 
-    # (inner) tar file
-    # will be wrapped in tarx
+    ## temporary (source) tar file
+    ## will encrypted and wrapped in tarx
+    [[ -d $tmp_dir ]] || mkdir -p $tmp_dir
+    tar_src=$tmp_dir/${dst_tar_get}_src.tar
 
-    ## append to (inner) tar archive
-    tar --append -f $tar_file -C $src_sub_dir $src_tar_get
+    for src_elem in "${src_arr[@]}"; do
+
+	s_el_sub_dir=$(dirname $src_elem)
+	s_el_tar_get=$(basename $src_elem)
+
+	tar --append -f $tar_src -C $s_el_sub_dir $s_el_tar_get
+
+    done
 }
 
 
@@ -685,7 +731,7 @@ crypt_first() {
 	encr)
 
 	    ## define file_in
-	    file_in=$tar_file
+	    file_in="$tar_src"
 
 	    ## define file_out
 	    file_out=$tmp_dir/$(basename $file_in).$round
@@ -775,13 +821,13 @@ crypt_last() {
 crypt_once() {
 
     ## only one round of en- or decryption
+    ## using one algorithm and no cipher cascade
     case $oper in
 
 	encr)
 
-	    file_in=$tar_file
-	    file_out=$dst
-	    #file_out=$src.crypt
+	    file_in="$tar_src"
+	    file_out="$tmp_dir/$dst_tar_get.crypt"
 	    ;;
 
 	decr)
@@ -816,7 +862,7 @@ crypt_exec() {
 	    [[ $opr == 'e' ]] && gnupg_opr='symmetric'
 	    [[ $opr == 'd' ]] && gnupg_opr='decrypt'
 
-	    #pass $pass_object | \
+		#pass $pass_object | \
 	        printf "$ropa" | \
 	    	gpg \
 	    	    --$gnupg_opr \
@@ -1115,8 +1161,7 @@ main() {
 
 	encr)
 
-	    #tar_create
-	    create_inner_tar
+	    tar_append
 	    encrypt
 	    ;;
 
