20200513_200413 vault dev to master

diff --git a/vault b/vault
--- a/vault
+++ b/vault
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # usage: sudo sh vault open <vault_file> <mountpoint>
-# usage: sudo sh vault close <vault_file>
+# usage: sudo sh vault close <vault_file> #TODO mountpoint #TODO mapperID
 # usage: sudo sh vault create <vault_file> <size>
 
 set -e
@@ -61,7 +61,7 @@ check_mp_dir() {
 	## existence & emptyness
 	if [[ -d $mountpoint ]]; then
 		if [ "$(ls -A $mountpoint)" ]; then
-			printf "$mountpoint is not empty!\n" && exit 3
+			printf "$mountpoint is already a mountpoint\n" && exit 3
 		fi
 	else
 		printf "$mountpoint does not exist!\n" && exit 3
@@ -140,30 +140,207 @@ permissions() {
 }
 
 
-umounting() {
+check_close_entry() {
 
-	mp_and_map=$(lsblk -p $(losetup -j $vault_file | awk -F : '{print $1}') | tail -n 1)
-	mountpoint=$(echo "$mp_and_map" | awk '{print $7}')
-	printf "unmounting $mountpoint\n"
-	sudo umount $mountpoint
+	# all
+	if [[ $vault_file == "all" ]]; then
+		#umount all loopback devices (vlt_mapper)
+		vlt_names=$(lsblk -p | grep /dev/mapper/vlt_)
+
+		printf "$vlt_names\n"
+		#printf "sure to all unmount and close? (Y/n) "
+		#echo
+		#TODO yesno
+
+		printf %s "$vlt_names" |
+		while IFS= read -r line; do
+
+			mountpoint=$(printf $line | awk -F 'crypt ' '{print $2}')
+			sudo umount $mountpoint
+			printf "unmounted $mountpoint\n"
+
+			vlt_mapper=$(printf $line | cut -c 3- | awk '{print $1}')
+			sudo cryptsetup close $vlt_mapper
+			printf "closed $vlt_mapper\n"
+			clear_cache
+
+		done
+
+		printf "all closed succesfully\n"
+
+	fi
+
+
+	### vault_file
+
+	filetype=$(file $vault_file)
+
+	if [[ -n $(printf "$filetype" | grep -i 'luks encrypted') ]]; then
+		## $2 user entry ($vault_file) is a luks encrypted file
+
+		uuid=$(printf "$filetype" | awk '{print $11}')
+		printf "luks encrypted file has uuid: $uuid\n"
+
+		map_and_mp=$(lsblk -p $(losetup -j $vault_file | awk -F : '{print $1}') | tail -n 1)
+		vlt_mapper=$(echo "$map_and_mp" | awk '{print $1}' | cut -c 3-)
+		printf "$vlt_mapper "
+
+		mountpoint=$(echo "$map_and_mp" | awk '{print $7}')
+
+		if [[ -n $mountpoint ]]; then
+
+			printf "mounted to $mountpoint\n"
+			unmount
+
+		else
+
+			printf "is not mounted\n"
+			close_luks
+
+		fi
+
+	else
+
+		# $vault_file is no luks encrypted container
+		a=1
+
+	fi
+
+
+	### mountpoint
+
+	if [[ ! $(mountpoint $vault_file | grep not) ]]; then
+		## $2 user entry ($vault_file) is not not a mountpoint
+
+		mountpoint=$vault_file
+
+		# check if mountpoint has a vlt_mapper
+		vlt_mapper=$(lsblk -p | grep $mountpoint | awk '{print $1}' | cut -c 3-)
+
+		if [[ -z $(printf $vlt_mapper | grep '/dev/mapper/vlt_') ]]; then
+
+			printf "$vault_file is not mapped to a vlt loopback device\n"
+
+			exit
+
+		fi
+
+
+		if [[ -n $mountpoint ]]; then
+
+			printf "$vlt_mapper is mounted to $mountpoint\n"
+			unmount
+
+		else
+
+			#printf "is not mounted\n"
+			close_luks
+
+		fi
+
+	else
+
+		printf "no mountpoint detected for $vault_file\n"
+
+	fi
+
+
+	### vlt_mapper
+
+	## because of the code above; $2 user entry ($vault_file) is
+	## no vault file and no mountpoint,
+	## but still /can/ be a loopback device (vlt_mapper)
+	lsblk_p_grep_vf=$(lsblk -p | grep $vault_file)
+
+	if [[ -n $lsblk_p_grep_vf ]]; then
+		## $2 user entry ($vault_file) /can/ be a loopback device (vlt_mapper)
+
+		vlt_mapper=$(printf "$lsblk_p_grep_vf" | awk '{print $1}' | cut -c 3- | grep $vault_file)
+		## two times grep $vault_file;
+		## if $vault_file is (also) not loopback device (vlt_mapper)
+		## then $vlt_mapper will become an empty string
+
+		if [[ -n $vlt_mapper ]]; then
+			## $2 user entry ($vault_file) is a loopback device (vlt_mapper)
+
+			mountpoint=$(printf "$lsblk_p_grep_vf" | cut -c 3- | \
+				grep $vlt_mapper | \
+				awk -F 'crypt ' '{print $2}')
+
+			if [[ -n $mountpoint ]]; then
+
+				printf "$vlt_mapper is mounted to $mountpoint\n"
+				unmount
+
+			else
+
+				printf "is not mounted\n"
+				close_luks
+
+			fi
+		fi
+
+
+	else
+
+		printf "no loopback device detected for $vault_file\n"
+		echo
+		printf "invalid entry, please try again\n"
+		exit
+
+	fi
+
+}
+
+
+unmount() {
+
+	echo
+	printf "unmount & close? (Y/n) "
+
+	reply_single
+	echo
+
+	if printf "$reply" | grep -iq "^n"; then
+
+		exit
+
+	else
+
+		sudo umount $mountpoint
+		printf "unmounted $mountpoint\n"
+
+	fi
+
+	close_luks
 
 }
 
 
 close_luks() {
 
-	mp_and_map=$(lsblk -p $(losetup -j $vault_file | awk -F : '{print $1}') | tail -n 1)
-	mapping_name=$(echo "$mp_and_map" | awk '{print $1}' | cut -c 3-)
-	printf "closing luks $mapping_name\n"
-	sudo cryptsetup close $mapping_name
+	if [[ $option == "create" ]]; then
+
+		sudo cryptsetup close $mapping_name
+		printf "$mapping_name closed\n"
+		clear_cache
+		printf "$vault_file created succesfully\n"
+
+	else
+
+		sudo cryptsetup close $vlt_mapper
+		printf "closed $vlt_mapper\n"
+		clear_cache
+
+	fi
 
 }
 
 
 clear_cache() {
 
-	printf "clearing cache\n"
 	sudo sysctl --write vm/drop_caches=3
+	exit 0
 
 }
 
@@ -204,8 +381,6 @@ fi
 
 if [[ $option == "close" ]]; then
 
-	umounting
-	close_luks
-	clear_cache
+	check_close_entry
 
 fi
